# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/prefix-dev/recipe-format@main/schema.json
package:
  name: p4lang-pi
  version: "2024.9"

build:
  number: 2
  script: build.sh

source:
- git: https://github.com/p4lang/PI

requirements:
  host:
    - libboost-devel
    - libprotobuf=3.21
    - grpc-cpp
  build:
    - automake
    - cmake
    - make
    - libtool
    - flex
    - bison
    - ${{ compiler('cxx') }}
    - pkg-config
    - zlib
  run:
    - libprotobuf=3.21
