# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/prefix-dev/recipe-format@main/schema.json
package:
  name: p4lang-bmv2
  version: 2024.9

build:
  number: 0
  script: build.sh

source:
- git: https://github.com/p4lang/behavioral-model
  rev: ec328ab87fe10cea0e061a4d9eb15408fb49729a

requirements:
  host:
    - libevent
    - libopenssl-static
    # - nanomsg # deepvision/nanomsg
    - libboost-devel
    - gmp
    - libevent
    - libpcap
    - python=3.9
    - thrift-cpp
    - p4-pi
  build:
    - automake
    - cmake
    - make
    - libtool
    - flex
    - bison
    - ${{ compiler('cxx') }}
    - pkg-config
  run_exports:
    weak:
      - ${{ pin_subpackage('p4-pi', exact=True) }}
  run:
    - p4-pi